### ISSUE TITLE
Instalation

### ISSUE THREAD

**Issue by jrotaetxe** [thess/callattendant#1]
Know is a stupid question, but please, help...
How do you install this specific fork compared to original?
Thank you in advance

**Comment by roycewilliams** [comment]
No, it's a good question! The [general install steps](https://github.com/emxsys/callattendant/wiki#installation) from the docs should be the same, with this modification:

Python pre-3: `pip install 'callattendant @ git+https://github.com/thess/callattendant'`

Python 3+: `pip3 install 'callattendant @ git+https://github.com/thess/callattendant'`

**Comment by jrotaetxe** [comment]
Thank you very much, Mr Williams!!!
