### ISSUE TITLE
Something else about .wav files...

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#10]
Maybe it is just me and my install. But after installing following instructions (I did, however, use pip rather than pip3 since I am on Ubuntu and read somewhere that this was a more appropriate way to go), I ended up with an empty resources folder under ~/.callattendant and I had to manually copy the .wav files from ~/home/davidw/callattendant/lib/python3.10/site-packages/callattendant/resources into that location in order to stop getting failures when starting callattendant. Is that intended? Thanks

**Comment by thess** [comment]
I had not added any new .wav recordings of my own to this repo. I had made a set of new messages (using an online text-to-speech service) that do match the operation of Callattendant but then neglected to add them to the repository. The installation (setup.py) omits them on-purpose. I will add a new set of example messages and update the installer (and perhaps the app.cfg.sample as well) this week.

Feel free to create your own - You can easily convert any .mp3 (preferably mono) to the correct .wav format using ffmpeg.
Example: `ffmpeg -i my-greeting.mp3 -ar 8000 -c:a pcm_u8 my-greeging.wav`

**Comment by thess** [comment]
New set of default WAV files and copy default notification messages to config if missing. Custom messages in `app.cfg` already in place will not be overridden.

Closed by: db8d1ce94e90b4ad56874e818249eb6e31f052d1 and 6e55475360a9676f9a5cd409f315aca0677ea618

**Comment by whitedavidp** [comment]
Hello Ted, and thanks...
    I see a whole bunch of changed stuff in github.
        What is the right way to update an already "working" venv? I
        have tried to find and copy over the new stuff. But I am left
        with a well-hosed-up mechanism.
    David
    
    
    On 1/17/2024 11:48 AM, Ted Hess wrote:
    
    
      New set of default WAV files and copy default
        notification messages to config if missing. Custom messages in app.cfg already in place will not
        be overridden.
      Closed by: db8d1ce
        and 6e55475
