### ISSUE TITLE
Regular expression list documentation problem

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#15]
The following is what is shown at the top of the regular expression list page:

```
Edit the Block (blacklist) and Permit (whitelist) regular expressions here. Each line of text should have the format:
   <regex> [: <description>]
that is, a [regular expression](https://docs.python.org/3/library/re.html#regular-expression-syntax), **optionally followed by a colon** and a human-readable description of who is being black or whitelisted.
```
The problem with this is the part in bold. The code in webapp.py's stringlist2dict() explicitly splits the lines based up ": " - note the trailing white space:

```line.split(': ', 1)```

Without it, the regular expressions are not executed properly. I have discovered this via personal experience.

So this should actually be changed to something like:

```
optionally followed by a colon, a single white space, and a human-readable description of who is being black or whitelisted.
```

FYI

**Comment by thess** [comment]
Clarified in 1.6.5 release. Added light syntax check for rule comment format (Follows YAML std.)
