### ISSUE TITLE
RD02-D400 modem

### ISSUE THREAD

**Issue by HuguesReynaud** [thess/callattendant#2]
Hi, I am trying to use a [Conexant/Dell rd02-d400](http://www.ascendtech.us/dell-0nw147-56k-external-usb-modem_i_mdusbdell0nw147.aspx) with my callattendant.

It is detected and set as a "Conextant-based modem" : 
`Initializing Modem
Opening serial port
Looking for modem on /dev/ttyACM0
_send_and_read('AT','OK',5)
'\r\n'
'OK\r\n'
_send_and_read('ATI0','OK',5)
'\r\n'
'56000\r\n'
'\r\n'
'OK\r\n'
******* Conextant-based modem detected **********
Serial port opened on /dev/ttyACM0
Initializing modem settings
_send_and_read('ATZ','OK',5)
'\r\n'
'OK\r\n'
_send_and_read('ATV1','OK',5)
'ATV1\r\r\n'
'OK\r\n'
_send_and_read('ATE0','OK',5)
'ATE0\r\r\n'
'OK\r\n'
_send_and_read('AT-SCID=1;+VCID=1;-STE=3','OK',5)
'\r\n'
'OK\r\n'
_send_and_read('AT&W0','OK',5)
'\r\n'
'OK\r\n'
_send_and_read('AT&V','OK',5)
'\r\n'
'ACTIVE PROFILE:\r\n'
('B1 E0 L2 M1 N0 Q0 T V1 W0 X4 Y0 &C1 &D2 &G0 &J0 &K3 &Q5 &R1 &S0 &T5 &X0 '
 '&Y0\r\n')
('S00:000 S01:000 S02:043 S03:013 S04:010 S05:008 S06:003 S07:090 S08:001 '
 'S09:006\r\n')
('S10:014 S11:085 S12:050 S18:000 S25:005 S26:001 S36:007 S38:020 S46:138 '
 'S48:007\r\n')
'S95:000 \r\n'
'\r\n'
'STORED PROFILE 0:\r\n'
'B1 E0 L2 M1 N0 Q0 T V1 W0 X4 Y0 &C1 &D2 &G0 &J0 &K3 &Q5 &R1 &S0 &T5 &X0 \r\n'
('S00:000 S02:043 S06:003 S07:090 S08:001 S09:006 S10:014 S11:085 S12:050 '
 'S18:000\r\n')
'S36:007 S40:104 S41:195 S46:138 S95:000 \r\n'
'\r\n'
'STORED PROFILE 1:\r\n'
'B1 E1 L1 M1 N0 Q0 T V1 W0 X4 Y0 &C1 &D2 &G0 &J0 &K3 &Q5 &R1 &S0 &T5 &X0 \r\n'
('S00:000 S02:043 S06:003 S07:090 S08:001 S09:006 S10:014 S11:085 S12:050 '
 'S18:000\r\n')
'S36:007 S40:104 S41:195 S46:138 S95:000 \r\n'
'\r\n'
'TELEPHONE NUMBERS:\r\n'
'0=                                     1=\r\n'
'2=                                     3=\r\n'
'\r\n'
'OK\r\n'
Modem initialized
`

I though everything was fine, but when I make an inbound call, the only output I get is : 
`RING
RING LED blinking: 10 times`

No phone number or anything else.

I just looked at the "modem.py" file and it seems that the conexant settings are specific to the Zoom 3095 modem. I suppose it could be the wrong config for my device, but I have no idea how to deal with that. Do you have any advice ?

**Comment by roycewilliams** [comment]
The list of modems with full voice capabilities is somewhat narrow - they're not fully documented here, but other projects (like CallBoot) have lists of devices that should, in theory, be compatible (but extra work may be needed):

https://callboot.net/hardware.html

On that page, it lists the specific Conexant modems with the CX93001 chipset. But this Ezlo thread says that Caller ID support is "broken" on the RD02-D400 modem:

https://community.ezlo.com/t/using-modem-as-a-telephone-ring-sensor/170586/7

Downthread, there's a workaround for another mentioned modem - the USR 5686E - that says to use `set initcid = "AT#CID=1"` to initialize the CID, but I do not know if that same tweak would help in your case.

**Comment by thess** [comment]
Assuming you have caller ID from your carrier and/or ATA setup, here are some things to check.

- Is caller ID shown on different instrument/phone enabled for CID attached to same phone line
- Connect to the Modem serial port and issue `AT+GMR` to see the chip designation (verify CX930xx)
- Make sure the country code is set for your region/service (`AT+CGI?` to query, `AT+CGI=<code>` to set it).
  List of codes: (B5 is US) http://www.katpatuka.org/pub/doc/t.35.html

In general, we should work with any Conexant CX930xx modem chipset. (Mine reports: `CX93001-EIS_V0.2013-V92`). Any mention of Zoom modems in `modem.py` are probably outdated. The modem setup commands issued by Callattendant should enable caller ID snooping if it is present on the line between rings.

Update: One other thing I should mention... I often see the caller ID show up after the 2nd ring (not always). Reviewing your posted output, I don't see anything after the 2nd ring. Do you have Callattendant setup to answer on 2nd ring by any chance?

**Comment by HuguesReynaud** [comment]
Thank you both for your answers ! Here is what I get from minicom : 

AT+GMR
+GMR: CX93001-EIS_V0.2002-V92 
OK

AT+VCID?                                
1                                                                          
OK

AT+GCI?
+GCI: 3D (I am in France so it's good for me)
OK

Then I make an inbound call : 
RING
RING
RING
...

- CID is working on my phone on the same line.
- For now, all my *_RINGS_BEFORE_ANSWER variables are set to 0.

**Comment by thess** [comment]
I'm afraid your version has non-functional caller ID.

To verify, issue: `AT-PV`. If the return is `F10574` you are out-of-luck

Ref: https://sourceforge.net/p/ncid/discussion/275237/thread/2997ed66/?page=1#455f/de9f

**Comment by thess** [comment]
One final remark here -- Found some additional info on Dell modem from the NCID project:
https://en.wikipedia.org/wiki/Network_Caller_ID

Footnote on Dell modem:
`Note G: CallerID intentionally disabled by vendor in EEPROM patch. CallerID can be reenabled in any CX93001-based modem via simple RAM patch after ATZ command: AT!4886=00 for Bell FSK countries, AT!4886=01 for V23 FSK (Japan), AT!4886=02 for ETSI FSK (France, Italy, Spain), AT!4886=03 for SIN227 (UK), AT!4886=05 for ETSI DTMF. Sometimes additionally AT!4892=FF may be required.`

If you decide to give this a try - let us know what happens.

**Comment by roycewilliams** [comment]
Wow, what a great find, @thess !

If it works reliably ... naively, how hard would it be to make callattendant auto-detect such specific modem variants (perhaps by USB vendor:model?), and then branch to pass the appropriate corresponding specific AT command RAM patches?

**Comment by thess** [comment]
It could be automated as you say. However, the complexity is determining your telco encoding scheme/country. Examining the country code is a start.

I was thinking of adding an optional modem init string to the config. Simpler to implement but requires end user customization.

**Comment by HuguesReynaud** [comment]
I first thought it was time to give up :
AT-PV
F10574
OK

But I then tried the RAM patch : 
AT!4886=02 (again, for France)
OK  
                                    
Inbound call :                                     
DATE = 1213                             
TIME = 2153                             
NMBR = 06xxxxxxxx                                                    
RING  

The RAM patch is a success, I now have CallerID working like a charm ! After a callatendant restart, my inbound calls are screened as expected. 
I finally made a small change in "modem.py" to initialize the modem with the patch (only a static thing for my use case, though).
Thank you again guys for helping me !

**Comment by thess** [comment]
One last request if you don't mind. It's OK if you don't have the time.

I would like to know if the patch is persistent (that is, stored in EEPROM). To test:
- remove change to `modem.py` (disable patch at startup)
- unplug modem and re-connect it (initialize itself)
- test for CID. If OK then patch is permanent. If not, put your mod back in play if you want.

Update (12/16): No need to bother -- It is NOT persistent. Must be done after reset (ATZ)

**Comment by HuguesReynaud** [comment]
I can confirm it's not persistent : I did the patch then reboot and I had to do it again to get CID working. This is why I choose to put the patch directly in the modem initializing file `modem.py`
If you want to try to automate this patch as suggested earlier, I would gladly help by testing it on my hardware !

**Comment by thess** [comment]
Thanks for your help. I am closing this issue as solved with v1.6.3 release:  02010cb
https://github.com/thess/callattendant/releases/tag/v1.6.3

See note in README regarding Dell modems.
