### ISSUE TITLE
Really minor spelling type error in the web UI

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#21]
In the string returned under the else below, add the word "be"...

Thanks

@app.route('/callers/permitnextcall')

def Callers_permit_next_call():

    nextcall = NextCall(app.config['MASTER_CONFIG'])

    if nextcall.toggle_next_call_permitted():

        return '1Next call will be permitted.'

    else:

        return '0Next call will **be** handled normally.'

**Comment by thess** [comment]
Not spelling -- grammar.
d0bcbed

**Comment by whitedavidp** [comment]
Right you are! Thanks
