### ISSUE TITLE
Minor Github Main Screen Error

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#23]
The link for "Screenshots of the home page as seen on an IPad Pro and a Pixel 2 phone" in the Overview section is not found:

https://github.com/thess/callattendant/raw/master/docs/dashboard-responsive.png

**Comment by thess** [comment]
Right. Link should be:
https://github.com/thess/callattendant/blob/fmsentry/docs/dashboard-responsive.png

**Comment by thess** [comment]
d0bcbed
