### ISSUE TITLE
Supplied app.cfg has errors

### ISSUE THREAD

**Issue by b-morgan** [thess/callattendant#30]
The supplied app.cfg has errors (see below). The diff which follows reflects the changes necessary to eliminate the errors. If app.cfg is intended to mirror the settings when no config file is present, then there may be other errors I haven't discovered yet.

```
pi@rpi3bplus:~/.callattendant $ callattendant --config=app.cfg
Command line options:
  --config=app.cfg
  --data-path=None
  --create-folder=False
The VOICE_MAIL_MESSAGE_FOLDER symlink is not present. Creating /home/pi/.local/lib/python3.9/site-packages/callattendant/userinterface/static/messages symlink
* BLOCKED_ACTIONS must include either 'answer' or 'ignore'
* SCREENED_ACTIONS must include either 'answer' or 'ignore'
* PERMITTED_ACTIONS must include either 'answer' or 'ignore'
ERROR: Configuration is invalid. Please check app.cfg
pi@rpi3bplus:~/.callattendant $
```
```
pi@rpi3bplus:~/.callattendant $ diff app.cfg debug.cfg
112c112
< BLOCKED_ACTIONS = ("greeting", "voice_mail")
---
> BLOCKED_ACTIONS = ("answer", "greeting", "voice_mail")
126c126
< SCREENED_ACTIONS = ("greeting", "record_message")
---
> SCREENED_ACTIONS = ("answer", "greeting", "record_message")
146c146
< PERMITTED_ACTIONS = ("greeting", "record_message")
---
> PERMITTED_ACTIONS = ("ignore",)
```

**Comment by b-morgan** [comment]
The file app.cfg.example is very different than the file app.cfg that appears in the `.callattendant' directory after installation. I'm not sure where app.cfg comes from.

See https://github.com/thess/callattendant/issues/31 for problems with app.cfg.example

**Comment by thess** [comment]
The default `app.cfg` is a copy of `app.cfg.example` installed when the `--create-folder` option is specified and the `.callattendant` directory does not exist. Otherwise, it is just what is found there from a previous version/installation. New items will have a built-in default.

So, in your case -- I suspect something left over from the past.
