### ISSUE TITLE
app.cfg.example line 192

### ISSUE THREAD

**Issue by b-morgan** [thess/callattendant#31]
Line 192 in https://github.com/thess/callattendant/blob/fmsentry/callattendant/app.cfg.example causes an error.

The line is `please` and probably needs to be removed.

**Comment by thess** [comment]
Yes, just noticed the stray line myself.

**Comment by thess** [comment]
Fixed in: https://github.com/thess/callattendant/commit/d9ac7a5ac5a421fc1d656ea2652e0a19ad9cef99
