### ISSUE TITLE
Screened call - Press 0 or 1 not working

### ISSUE THREAD

**Issue by b-morgan** [thess/callattendant#32]
I am using a StarTech USB56KEMH2 modem on a Libre LePotato. Permitted and Blocked lists are working but a Screened call plays the greeting telling me to press either 1 or 0. Neither of these appears to work.

I have enabled debug but I'm not sure what to look for.

**Comment by thess** [comment]
You could start with describing the test as your ran it. What you did. What you expected to happen and what actually happened. Also, supply the actual log you recorded showing, at least, the phone being answered, and all interactions. Please remove/obscure any private information like phone #'s, passwords, etc.

**Comment by b-morgan** [comment]
After a little code inspection, I have discovered that while the greeting played says (in part) "press 0 or press 1", a `SCREENED_ACTIONS = ("answer", "greeting", "record_message")` doesn't execute the code in `voice_messaging_menu` which is the only place (I can find) where `wait_for_keypress` is called.

I'll change `SCREENED_ACTIONS` and try again. I believe there should be a different .wav file to play when `SCREENED_ACTIONS` contains "record_message" but that can wait until I figure out this issue.

**Comment by b-morgan** [comment]
Changing `SCREENED_ACTIONs` worked. Probably should be changed in the defaults.

I believe `BLOCKED_ACTIONS = ("answer", "greeting", "voice_mail")` never gets to the "voice_mail" part. Should this be changed in the defaults?

**Comment by thess** [comment]
You are right -- I ought to work a bit on the OOTB experience. :wink:

As it stands now, the greeting and the behavior do not match.

**Comment by thess** [comment]
Closed in release v1.7.3
