### ISSUE TITLE
Not an issue, really. More like newbie questions...

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#4]
Hello and thanks in advance for helping this newbie...

I am trying to do some basic testing so I can see how this might work for me. For this purpose, I am using an old Hayes Modem [<http://articles.yuikee.com.hk/technotes/POTS/accura288.html>](http://articles.yuikee.com.hk/technotes/POTS/accura288.html). I know it supports caller id. And it seems from what is noted in the reference page "it appears that most voice commands are simply not implemented".  Rats!

For my simple needs, I really don't need/want anything beyond this:

1. Incoming call with caller id info comes in

2. The number and/or name from caller id info is checked

3. If determined to be blocked, simply hang up on the call and wait for the next call

4. If determined NOT to be blocked, simply let the phone ring and ring - at least until our telecom's voice mail answers

It seems like the modem's caller id support SHOULD be enough to get this done and I really am not sure that I need any real voice call support in the modem. Is this correct?

This modem has 2 RJ-11 ports. I have it set up with the line coming from my telecom's fiber modem goes into the line port and then the phone port is connected to all of the other extensions in my home. When an incoming call arrives, all of the phone extensions ring...

I have been able to force the app to directly open my modem's serial port file (without needless searching as it is always on /dev/ttyS2). And it seems like things are at least partially working after I changed this line in modem.py:

ENABLE_FORMATTED_CID = "AT+VCID=1"

to

ENABLE_FORMATTED_CID = "ATS0=2#CID=1"

and setting the following in the config file (as I am in the USA):

PHONE_DISPLAY_FORMAT = "###-###-####"
COUNTRY_CODE = "B5"
SCREENING_MODE = ("whitelist", "blacklist")
BLOCK_ENABLED = True
BLOCK_SERVICE = "NOMOROBO"
BLOCKED_ACTIONS = ("answer",)
SCREENED_ACTIONS = ("answer",)
PERMITTED_ACTIONS = ('ignore',)

I then started the app, went to the web interface, and added my cell phone's number (xxx-yyy-zzzz below) to the block list and tried to call. In the stdout, I see:

    b'RING\r\n'
    b'DATE = 0103\r\n'
    b'TIME = 0953\r\n'
    b'NMBR = xxxyyyzzzz\r\n'
    b'NAME = WIRELESS CALLER\r\n'
    > Queueing call xxxyyyzzzz for processing
    Adding to caller queue:
    {'DATE': '0103',
     'NAME': 'WIRELESS CALLER',
     'NMBR': 'xxxyyyzzzz',
     'TIME': '0953'}
    Incoming call from xxxyyyzzzz
    > Checking next-call-permitted
    > Checking blacklist(s)
    > New call log entry #1
    ['WIRELESS CALLER',
     'xxxyyyzzzz',
     'Blocked',
     '',
     '03-Jan',
     '09:53 AM',
     '2024-01-03 09:53:18']
    --> xxxyyyzzzz Blocked:
    > Going off hook...
    b'RING\r\n'
    b'RING\r\n'
    >>> Lock acquired in pick-up()
    _send_and_read('AT+FCLASS=8','OK',5)
    b'\r\n'
    b'ERROR\r\n'
    >>> _read_response returned ERROR
    'Error in pick_up: Failed to put modem into voice mode.'
    >>> Lock released in pick-up()
    Waiting for next call...

HOWEVER,

The phone kept ringing and ringing. It was not hung up as I'd hoped it would be.

Also, I note that my one caller id enabled handset does NOT show any caller id information. Without using this app, it normally does. So I wonder if this app is somehow eating this information and not passing it along? Is that expected? Is it a function on how I have wired the phone line cables (see above)?

Thanks very much for any insight you can give me. I feel that I am close to an acceptable "solution" here.

Happy new year!

**Comment by thess** [comment]
In general, support for non-voice capable modems was not any part of callattendent's design. I'm glad to see that you are doing quite well creating your special variant including changes to the modem handling and overall operational behavior. Enjoy.

**Comment by whitedavidp** [comment]
I know this has been closed. But I want to add that I finally have a stable and working system using an ancient, external, caller-id capable, SupraFax modem. It turned out that the Hayes unit I was originally testing (and presumed would be higher quality than the SupraFax), while caller-id capable, performed this function poorly and inconsistently. And this is why my results were so strange. When I decided to swap-in the SupraFax I started getting bomb-proof and consistent results. I did need to update the caller-id command in the modem code. But that was pretty simple.

Of course, using such an ancient modem prohibits the use of the vast majority of functionality in Call Attendant. And to make it work, I had to comment-out a bunch of code that invokes these functions. I am left with a Call Attendant which, upon an incoming call, simply consults the allow number/names lists and, if found there, ignores the call. Otherwise it simply answers and then immediately hangs-up. This is a bit hard-core and it may hang up on some calls you actually want to take. But the calls are still logged in both Call Attendant and in the log found on caller-id enabled handsets. So it is pretty easy to just add those numbers to the allow lists.

Now, every time the phone rings once and that is all, a giant smile crosses both my wife and my faces! It is a terrific improvement! With this success, I have gone ahead and ordered a USR modem and will switch over to it once it finally gets here. But for those who can appreciate the increased silence create by my simple approach using a modem otherwise destined to the electronics recycle, it may be quite cool to add configuration options for this simple, but effective, mode.

Thanks

**Comment by roycewilliams** [comment]
@whitedavidp If there was an elegant way to turn your commenting-out into a configuration option, I personally would find that to be a useful "use at your own risk, but here's the knob" feature add for the project. It would make it much easier  for a much larger set of simple use cases, and also allow use of a wider variety of modems to fit those use cases (leaving the voice-capable modems more available for the rest of us!) :D
