### ISSUE TITLE
Change or Configure MQTT retention on publishing?

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#43]
As I have started to investigate the MQTT stuff, I have noticed that my two MQTT clients (on Android and Windows) were getting repeated messages. Seemed like they were happening when the clients started/re-started. So I posted [here on Reddit](https://www.reddit.com/r/MQTT/comments/1cktz8y/newbie_needs_help_getting_repeated_messages/) about this since I am an MQTT idiot.

I got a quick response suggesting that this line in mqttindicators.py may be the cause:

`client.publish(self.topic_prefix + topic, message, retain=True)`

They said "When you set retain=true for a message is basically tells the broker to remember the message and to send it to everyone who subscribes to that topic in the future. So when your client reconnects and subscribes again it receives the message again."

So this may be a candidate for change or configuration?

As I wrote in that post, at least for me, "The sending/receipt of these messages are far from mission-critical. I am just trying to compensate for a lack of caller-id-enabled phone handsets by sending MQTT messages to Android smart phones and Windows desktops on my LAN. I really don't need/want high levels of service quality and repeated sending of messages. I am seeking a one-and-done kind of thing. So when the phone rings, the screening app sends out the MQTT messages and I am trying to show them on the receiving devices in semi-real time so I can know who is calling at that time (and know if I want to pick up or not)."

Now I am not sure that my use-case is consistent with other CA users. As I said earlier, I am an MQTT idiot. Thanks!

**Comment by thess** [comment]
Think of it this way - The MQTT topics are reflecting the state changes of virtual LEDs and not a series of events. For that reason I chose `retain=true`. When a client connects it then obtains the current state of the Callattendant. When Callattendant starts-up or shuts-down, it publishes the current state of the indicators (except `LastCallerID`). The client must track state changes itself.

If implemented without retention, there would be no way to determine the current state. Callattendant is not listening to any MQTT topics - no reason.

**Comment by thess** [comment]
Read you reddit posting - Thanks for the free publicity.

Regarding mosquitto persistence -- the mechanism is for preserving topics marked for retention when the server restarts/reboots. Otherwise, the topics would no longer be preserved.

**Comment by whitedavidp** [comment]
As far as I am concerned, there is no way to give your fork of CA enough good publicity!

In my setup, I really only care about Accepted calls. Everything else just gets hung-up upon and that's fine. If I hear the phone ring once and stop, I know it is 99% spam but if I want to know more, I can check the CA dashboard and see. But sometimes I don't want to pick up some Accepted calls (but not all). I have only a single phone extension with a caller-id display. It takes too long for me to get to the dashboard in this case to see the caller-id info and respond. So I first got interested in the MQTT stuff as I wanted to flash notifications of incoming, Accepted calls to my Android and Windows devices. I hoped that the MQTT response time would be faster and allow me to more easily decide if I want to actually pick up an Accepted call.

I now realize that the original MQTT stuff was not at all intended to be this way and you had already started working on something more to fit my needs in v 2.0. I guess that even with the caller-id in MQTT, folks might want to have the persistence. But I think (am not yet sure) that I will not in my case. If so, it is easy enough for me to change True to False on that one line of code.

Thanks

**Comment by thess** [comment]
Changed my mind -- added MQTT_NOTIFICATION_TYPE to config. Choose either EVENT or STATE opts.

Closed by cf711acbc6910a6a99fe96d41603174256bb3c38

**Comment by thess** [comment]
[V2.0.4](https://github.com/thess/callattendant/releases/tag/v2.0.4) released
