### ISSUE TITLE
Caller Name in Top Permitted Callers on Dashboard Are Not Ideal...

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#55]
I have noticed that in the Top Permitted table on the Dashboard, the name shown along with the count for a given number may not be as informative as it could be. Consider this and look at the number 425-xxx-9625:

![CA_Desktop](https://github.com/thess/callattendant/assets/12023355/8363a342-8fcf-4525-921f-cf9509c6c79e)

It is shown with the name "Potential Spam" - which it originally was. But I have since allowed the number and added a real name (mine) so in the call log for that number you see:

![CA_Call_Log](https://github.com/thess/callattendant/assets/12023355/37043661-7c04-4adb-9201-6786cda651fa)

It would be good if the Top Permitted Callers table reflected the updated name.

**Comment by thess** [comment]
Agree - good idea. See e1b2403e2537844fb5b32e116137424ada68ccf6 or wait for another release (none sched ATM).

**Comment by whitedavidp** [comment]
I will try to get a look soon. Thanks as always....

**Comment by thess** [comment]
Closed with release of v2.0.7
