### ISSUE TITLE
Not getting date/time on console log

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#59]
I have tried setting CA to all combinations of development/production, debug/not and in no case do I end up seeing date/time stamps in the console log. What am I doing wrong here? Thanks

![Capture](https://github.com/thess/callattendant/assets/12023355/54793324-4a5b-4799-bef6-3f2ddbc95f78)

**Comment by thess** [comment]
CA itself does (very) simple print statement logging, no additional information is automatically added. When running as a service, the `systemd` service provides the time-stamping, etc. That's why when viewing with `jounalctl`, you get time-stamps.

**Comment by whitedavidp** [comment]
Thanks. That explains what I see perfectly. On my own CA install, I can run via systemd. On another recent install for a friend, I am running a chroot'ed Linux on Android and there is no systemd support - only sysv. And there is where I was not seeing the date/time stamps. Sorry for the bother...

**Comment by roycewilliams** [comment]
I solved this problem outside of callattendant by using a classic Unix utility called 'ts' that prepends a date stamp to all records of output. See:

https://github.com/roycewilliams/callattendant-resources/blob/main/run-with-logging.sh

**Comment by whitedavidp** [comment]
> I solved this problem outside of callattendant by using a classic Unix utility called 'ts' that prepends a date stamp to all records of output. See:
> 
> https://github.com/roycewilliams/callattendant-resources/blob/main/run-with-logging.sh

That is freaking fantastic, Royce! I had to apt-get install moreutils to get ts but that wasn't too hard once I discovered that is where the command lives. Thanks so much! Wow!

**Comment by roycewilliams** [comment]
@whitedavidp Great! And I've also added a comment to the script to help folks locate `ts` faster in the future - thanks for the nudge! :D

> ` 'ts' is usually part of the 'moreutils' package.`
