### ISSUE TITLE
Inaccurate text in Call Detail page

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#61]
If the call was blocked due to blocked name pattern list...

It clearly shows the call as blocked in red, as it should be.

But below it says "This caller is allowed but..." and this seems at best confusing and at worst incorrect.

![Capture](https://github.com/thess/callattendant/assets/12023355/7982fc67-5635-4fee-88ed-b079bdb172c8)

Best

**Comment by thess** [comment]
See if 452e847a44f95a06463f7b815806f53c0f44e957 meets your expectations.

**Comment by whitedavidp** [comment]
> See if [452e847](https://github.com/thess/callattendant/commit/452e847a44f95a06463f7b815806f53c0f44e957) meets your expectations.

That's it exactly (from my perspective anyhow). As always, thanks! This is so great!

**Comment by thess** [comment]
Closed with release of v2.0.7
