### ISSUE TITLE
Strange Results When Searching Call Log

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#62]
Hi. We get a number of calls where the CID name is something like "Washington Call" and I wanted to see if these ever came from other states. So in the dashboard, on the call log page, I performed a name search on call. The results are strange:
![Capture](https://github.com/thess/callattendant/assets/12023355/f6b96424-4d05-4f02-8357-2c83b54de824)
As you can see, it says there are 77 rows returned, that rows 1-25 are being displayed, and that there are multiple pages in the search results. However, only 8 rows are shown. Clicking on the other pages give a result like this:
![Capture3](https://github.com/thess/callattendant/assets/12023355/e6a8da5d-de4c-4c1f-ad55-aece94f0cb9e)

So using a Sqlite DB Browser, I issued the query:
`select * from calllog where name like '%call%'`
and I get the following results:
![Capture2](https://github.com/thess/callattendant/assets/12023355/1fb0bb9b-b3af-4cf2-bff8-8ff36fb9a852)
As you can see, the query here also claims 77 rows in the result. However, I can see all of them in the DB browser. Strange!

I checked the monitor on CA while performing this query from the dashboard. I saw nothing untoward occur - like an error.

This may prove difficult to reproduce. And it is strange indeed. But it is not a major problem (at least for me).

Thanks, as always...

**Comment by thess** [comment]
Not too difficult to reproduce... Was a matter of an incomplete feature implemented 4yrs ago by original author.
Fixed in 6abf15f2fe05ba7af1f27b34ed56dd9a6c382ee8

Thanks for rooting this out

**Comment by whitedavidp** [comment]
That seems to produce far better results. It turns out that many of the 77 rows returned to me were for numbers added to the permit list with a "real" name. Now I get only 9 rows and that seems about right.

As always, thanks!

**Comment by b-morgan** [comment]
The "Release" is 2.0.4 and this commit is 2.0.7. How do I keep my install up-to-date?

**Comment by thess** [comment]
Closed with release of v2.0.7
