### ISSUE TITLE
How to convert to this fork? 

### ISSUE THREAD

**Issue by whitedavidp** [thess/callattendant#7]
Sorry for all of my newbie questions...

I started out with one of the other forks (also based on galacticstudios' version - specifically this one <https://github.com/advfr/callattendant/> as it had all the GPIO stuff commented-out). I now want to move to this fork as it appears to be the most active I have found so far and, perhaps, most advanced.

I have everything working in my current version with the service running on start via systemctl and the stuff already configured in the .calltattendant folder. I hope to perturb all of this to the minimum extent possible. But I have no idea how to best accomplish this.

Thanks in advance for any tips.

**Comment by thess** [comment]
The details of how to merge multiple development branches across 2 or more repositories AND have the complete set of all the mods you want to keep is outside the scope of what we are doing here. You may find some useful topics on this subject on other sites which can help you develop your skills in this area. Understanding basic git branching and merging is a good start. Creating patch files from git-diffs and re-applying them to a different repository is not always straight forward.

Best success going forward. ;)
